name: Deploy Angular Application

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The version to deploy'
        required: false
        type: string
        default: 'latest'
   # secrets:
   #   required: [DEPLOYMENT_SECRET]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm install

      - name: Build Angular application
        run: npm run build

      - name: Test and Deploy
        run: |
          npm test -- --watch=false --browsers=ChromeHeadlessNoSandbox
          echo "Version: ${{ inputs.version }}"
          # Add your Angular deployment commands here
     #   env:
     #     DEPLOYMENT_SECRET: ${{ secrets.DEPLOYMENT_SECRET }}
     
      - name: upload-artifacts
        uses: actions/upload-artifact@v4
        with:
          name: upload-artifacts
          path: 'dist/hello-world-app'
